apiVersion: v1
kind: Namespace
metadata:
  name: webstore-uat
  labels:
    istio-discovery: enabled
    istio.io/dataplane-mode: ambient
    # istio.io/use-waypoint: waypoint-proxy
    ambient.istio.io/redirection: enabled