# This file contains two Kubernetes Secret resources for a Java-based TODO application.
# The first secret, `todo-java-secret-plain`, uses `stringData` to store sensitive information in plain text. 
apiVersion: v1
kind: Secret
metadata:
  name: todo-java-secret-plain
type: Opaque
stringData:
  DB_USERNAME: "todo_user"
  DB_PASSWORD: "change-me"

---
# The second secret, `todo-java-secret-base64`, uses `data` to store the same information in base64-encoded format.
apiVersion: v1
kind: Secret
metadata:
  name: todo-java-secret-base64
type: Opaque
data:
  DB_USERNAME: "dG9kb191c2Vy"
  DB_PASSWORD: "Y2hhbmdlLW1lCg=="