apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "* * * * *"
  # Allow / Forbid / Replace
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: my-cronjob
              image: quay.io/rh_rh/utilities:ubi10-latest
              command: [ "/bin/sh", "-c" ]
              args:
                - |
                  echo "Executed at $(date)"
                  oc whoami
                  oc projects
                  oc get pods
                  oc exec todo-daemonset-5x8qh -- ls -al /
          restartPolicy: OnFailure