apiVersion: v1
kind: ConfigMap
metadata:
  name: canary-ip-routing
data:
  vip-xff-regex: ".*(47\\.131\\.17\\.204|119\\.234\\.45\\.87|119\\.234\\.45\\.110).*"
  split-xff-regex: ".*(10\\.128\\.[0-9]+\\.[0-9]+|10\\.129\\.[0-9]+\\.[0-9]+).*"
