---
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
spec:
  type: ClusterIP
  selector:
    istio: ingressgateway
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  - name: http-envoy-prom
    port: 15090
    targetPort: 15090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-ingressgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      istio: ingressgateway
  template:
    metadata:
      annotations:
        # Select the gateway injection template (rather than the default sidecar template)
        inject.istio.io/templates: gateway
      labels:
        app: istio-ingressgateway
        version: "1.0"
        # Set a unique label for the gateway. This is required to ensure Gateways can select this workload
        istio: ingressgateway
        # Enable gateway injection. If connecting to a revisioned control plane, replace with "istio.io/rev: revision-name"
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: istio-proxy
        image: auto       # The image will automatically update each time the pod starts.
        args:
          - proxy
          - router
          - --domain
          - $(POD_NAMESPACE).svc.cluster.local
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-ingressgateway-service-monitor
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  namespaceSelector:
    matchNames:
      - webstore-dev
  podTarget: true
  endpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 30s

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ingress-gateway
spec:
  to:
    kind: Service
    name: istio-ingressgateway
  port:
    targetPort: http
  tls:
    termination: edge

---
# Set up roles to allow reading credentials for TLS
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istio-ingressgateway-sds
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-ingressgateway-sds
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istio-ingressgateway-sds
subjects:
- kind: ServiceAccount
  name: default

# ---
# kind: NetworkPolicy
# apiVersion: networking.k8s.io/v1
# metadata:
#   name: deny-by-default
# spec:
#   podSelector: {}
#   policyTypes:
#     - Ingress

# ---
# kind: NetworkPolicy
# apiVersion: networking.k8s.io/v1
# metadata:
#   name: allow-same-namespace
# spec:
#   podSelector: {}
#   ingress:
#     - from:
#         - podSelector: {}
#   policyTypes:
#     - Ingress

# ---
# kind: NetworkPolicy
# apiVersion: networking.k8s.io/v1
# metadata:
#   name: allow-from-kube-apiserver-operator
# spec:
#   podSelector: {}
#   ingress:
#     - from:
#         - podSelector:
#             matchLabels:
#               app: kube-apiserver-operator
#           namespaceSelector:
#             matchLabels:
#               kubernetes.io/metadata.name: openshift-kube-apiserver-operator
#   policyTypes:
#     - Ingress

---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-from-openshift-ingress
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
  policyTypes:
    - Ingress

# ---
# kind: NetworkPolicy
# apiVersion: networking.k8s.io/v1
# metadata:
#   name: allow-from-openshift-monitoring
# spec:
#   podSelector: {}
#   ingress:
#     - from:
#         - namespaceSelector:
#             matchLabels:
#               network.openshift.io/policy-group: monitoring
#   policyTypes:
#     - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-istio
spec:
  podSelector: {}
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            istio-discovery: enabled
  policyTypes:
    - Ingress