# This is a sample network policy that denies all incoming traffic to pods in the "workshop" namespace.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: workshop1
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress: []