FROM registry.access.redhat.com/ubi10/ubi:10.1

RUN \
    dnf install -y \
            python3 \
            python3-pip \
            iputils \
            nmap-ncat \
        && dnf clean all

COPY resources/helloworld.txt /tmp/helloworld1.txt

ENV MYNAME "Red Hat"

CMD [ "/bin/tail", "-f", "/dev/null" ]