FROM registry.access.redhat.com/ubi10/ubi:10.1

ARG python_version=3
ARG version=1.0

RUN \
    dnf install -y \
            python${python_version} \
            python${python_version}-pip \
            iputils \
            nmap-ncat \
        && dnf clean all

COPY resources/helloworld.txt /tmp/helloworld-${version}.txt
ADD resources/RedHatFont-4.1.0.tar.gz /tmp/

ENV MYNAME "Red Hat"

WORKDIR /tmp

CMD [ "/bin/tail", "-f", "/dev/null" ]