# This is a ConfigMap for the todo-java application
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-java-configmap
  namespace: workshop
data:
  timezone: "Asia/Singapore"
  java_options: "-Xms256m -Xmx512m"
  spring_active_profiles: "prod"