# This is a sample pod for the todo-java application.
apiVersion: v1
kind: Pod
metadata:
  name: todo-pod
  namespace: workshop
  labels:
    app: todo-pod
spec:
  containers:
    - name: todo
      image: quay.io/rh_rh/todo-java:latest
      imagePullPolicy: Always

      # Resource requests and limits can be set for a container.
      resources:
        requests:
          cpu: 100m
          memory: 250Mi
        limits:
          cpu: 500m
          memory: 768Mi

      # Ports can be exposed from a container.
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP

---
# This is a sample service for the todo-java application.
apiVersion: v1
kind: Service
metadata:
  name: todo-pod-svc
  namespace: workshop
spec:
  selector:
    app: todo-pod
  ports:
    - name: http
      port: 8080
      targetPort: 8080

---
# This is a sample route for the todo-java application.
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: todo-pod-svc-workshop
spec:
  to:
    kind: Service
    name: todo-pod-svc
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: todo-pod-svc-workshop
#   annotations:
#     route.openshift.io/termination: edge
#     route.openshift.io/insecure-edge-termination-policy: Redirect
# spec:
#   rules:
#     - host: todo-pod-svc-workshop.apps.cluster-pvh8r.dyn.redhatworkshops.io
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: todo-pod-svc
#                 port:
#                   number: 8080