apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: product-sa-waypoint-impersonation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webstore-waypoint-impersonator
subjects:
- kind: ServiceAccount
  name: product-sa

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
        version: "1.0"
    spec:
      serviceAccountName: product-sa
      containers:
      - name: product
        image: quay.io/rh_rh/ossm3-product:dev
        imagePullPolicy: Always
        env:
        - name: REDIS_HOST
          value: "redis-service"
        ports:
        - containerPort: 6000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  ports:
  - port: 80
    name: http
    targetPort: 6000
  selector:
    app: product

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: product-service-monitor
  labels:
    openshift.io/user-monitoring: "true"
spec:
  targetLabels:
  - app
  selector:
    matchLabels:
      app: product
  namespaceSelector:
    matchNames:
      - webstore-dev
  endpoints:
  - port: http
    path: /metrics
    interval: 30s

# ---
# apiVersion: route.openshift.io/v1
# kind: Route
# metadata:
#   name: product-ingress
# spec:
#   to:
#     kind: Service
#     name: product-service
#     weight: 100
#   port:
#     targetPort: http
#   tls:
#     termination: edge

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: product
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
