apiVersion: apps/v1
kind: Deployment
metadata:
  name: mesh-ui
  labels:
    app: mesh-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mesh-ui
  template:
    metadata:
      labels:
        app: mesh-ui
    spec:
      containers:
      - name: mesh-ui
        image: quay.io/rh_rh/ossm3-webstore-ui:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: mesh-ui-service
  labels:
    app: mesh-ui
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: mesh-ui

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ui-service-monitor
  labels:
    openshift.io/user-monitoring: "true"
spec:
  targetLabels:
  - app
  selector:
    matchLabels:
      app: mesh-ui
  namespaceSelector:
    matchNames:
      - webstore-dev
  endpoints:
  - port: http
    path: /metrics
    interval: 30s